apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nettha-backstage-app"
  tags:
    - group:infrastructure
    - group:team-a
  annotations:
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
spec:
  type: service
  owner: group:backstage-admin
  lifecycle: experimental
  system: testing
