apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nettha-backstage-app"
  links:
    - url: https://dashboard.example.com
      title: Homepage
      icon: dashboard
    - url: https://dashboard.example.com
      title: Guide
      icon: help
  tags:
    - group:backstage-admin
    - group:backstage-cermati
  annotations:
    'jenkins.io/job-full-name': 'infra/grcd/grcd-frontend-prod-containerize'
    'github.com/project-slug': 'arnettha/nettha-backstage-app'
  jenkins: 'https://someurl.com'
spec:
  type: service
  owner: group:backstage-admin
  lifecycle: experimental
